name: Android CI Build

on:
  push:
    branches:
      - main # Ou la branche que vous souhaitez utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    # Le checkout place le contenu du repo à la racine du workspace.
    # Si gradlew est dans 'FactureDZ_Project' à la racine du repo cloné:
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./FactureDZ_Project # Ajusté pour pointer vers le dossier du projet Android

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon
      working-directory: ./FactureDZ_Project # Ajusté pour pointer vers le dossier du projet Android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: facture-dz-debug-apk
        path: ./FactureDZ_Project/app/build/outputs/apk/debug/app-debug.apk # Ajusté pour refléter la structure du projet

