name: Android CI Build

on:
  push:
    branches:
      - main # Ou la branche que vous souhaitez utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in workspace root # Pour vérifier la structure après checkout
      run: ls -la

    - name: List files in expected project directory # Pour vérifier la structure du sous-dossier
      run: ls -la ./home/ubuntu/FactureDZ_Project

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./home/ubuntu/FactureDZ_Project # Ajusté au sous-dossier du projet

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon
      working-directory: ./home/ubuntu/FactureDZ_Project # Ajusté au sous-dossier du projet

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: facture-dz-debug-apk
        path: ./home/ubuntu/FactureDZ_Project/app/build/outputs/apk/debug/app-debug.apk # Ajusté au sous-dossier du projet

