name: Android CI Build

on:
  push:
    branches:
      - main # Ou la branche que vous souhaitez utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./home/ubuntu/FactureDZ_Project # Ajustez si la racine du projet est différente après décompression

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon
      working-directory: ./home/ubuntu/FactureDZ_Project # Ajustez si la racine du projet est différente après décompression

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: facture-dz-debug-apk
        path: ./home/ubuntu/FactureDZ_Project/app/build/outputs/apk/debug/app-debug.apk # Ajustez le chemin si nécessaire

