name: Android CI Build

on:
  push:
    branches:
      - main # Ou la branche que vous souhaitez utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    # gradlew est à la racine du dépôt après le checkout
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      # working-directory: . # Pas besoin de working-directory ici, s'exécute à la racine

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon
      # working-directory: . # Pas besoin de working-directory ici, s'exécute à la racine

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: facture-dz-debug-apk
        # Le chemin est relatif à la racine du dépôt après checkout
        path: app/build/outputs/apk/debug/app-debug.apk 

