name: Android CI

on:
  push:
    branches:
      - main # Ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: List files in workspace root (debug)
      run: ls -la
      # This step is for debugging the file structure in the GitHub Actions runner

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      # working-directory: . # Default is root of checkout

    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug
      # working-directory: . # Default is root of checkout

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: facture-dz-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

